// <auto-generated />
namespace Prkn.Data.Local.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v003));
        
        string IMigrationMetadata.Id
        {
            get { return "202102051020497_v003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
