//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__ExtendedProperties
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string ParentName { get; set; }
        public string ObjectName { get; set; }
        public string Value { get; set; }
    }
}
