//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LOCALSETTINGSEntities : DbContext
    {
        public DB_LOCALSETTINGSEntities()
            : base("name=DB_LOCALSETTINGSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Prg> Prg { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
        public virtual DbSet<C__ExtendedProperties> C__ExtendedProperties { get; set; }
    }
}
