//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public string Device { get; set; }
        public string Device1 { get; set; }
        public string Device2 { get; set; }
        public string Device3 { get; set; }
        public string Device4 { get; set; }
        public string Device5 { get; set; }
        public string Device6 { get; set; }
        public string Device7 { get; set; }
        public string Device8 { get; set; }
        public string Device9 { get; set; }
        public string Device10 { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
