//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meetings()
        {
            this.Meeting_Content = new HashSet<Meeting_Content>();
            this.Meeting_JoinUser = new HashSet<Meeting_JoinUser>();
        }
    
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> MeetingTypeId { get; set; }
        public Nullable<long> MeetingStatusId { get; set; }
        public Nullable<long> RefNo { get; set; }
        public string MeetingTypeOther { get; set; }
        public string MeetingStatusOther { get; set; }
        public Nullable<System.DateTime> DatetimeSet { get; set; }
        public string Place { get; set; }
        public string Subject { get; set; }
        public string Firms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Content> Meeting_Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_JoinUser> Meeting_JoinUser { get; set; }
        public virtual Meeting_Status Meeting_Status { get; set; }
        public virtual Meeting_Type Meeting_Type { get; set; }
        public virtual Users Users { get; set; }
    }
}
