//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Rev
    {
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> CustomerContactId { get; set; }
        public Nullable<int> PeriodMonth { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<long> RefNo { get; set; }
        public Nullable<int> No { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Keyword { get; set; }
    
        public virtual Customer_Contact Customer_Contact { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
