//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store_Product()
        {
            this.Store_Warehouse = new HashSet<Store_Warehouse>();
            this.Store_WarehouseOut = new HashSet<Store_WarehouseOut>();
        }
    
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> BrandId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> TypeId { get; set; }
        public Nullable<long> UnitId { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public string ProductCodeFirstChar { get; set; }
        public string ProductCodeEndChar { get; set; }
        public string ProductIDFirstChar { get; set; }
        public string ProductIDEndChar { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Features { get; set; }
        public string Pic { get; set; }
        public string Score { get; set; }
        public string Info { get; set; }
        public string Keyword { get; set; }
    
        public virtual Store_ProductGroup Store_ProductGroup { get; set; }
        public virtual Store_ProductType Store_ProductType { get; set; }
        public virtual Store_ProductUnit Store_ProductUnit { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store_Warehouse> Store_Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store_WarehouseOut> Store_WarehouseOut { get; set; }
    }
}
