//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Warehouse
    {
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> BlockId { get; set; }
        public Nullable<long> AddressId { get; set; }
        public Nullable<long> OutActionId { get; set; }
        public string SerialNo { get; set; }
        public string RefNo { get; set; }
        public string StockNo { get; set; }
        public string StockNoAux { get; set; }
        public string Status { get; set; }
        public Nullable<float> PriceList { get; set; }
        public string PriceListCurrency { get; set; }
        public Nullable<float> PricePurchase { get; set; }
        public string PricePurchaseCurrency { get; set; }
        public Nullable<float> PriceSale { get; set; }
        public string PriceSaleCurrency { get; set; }
        public Nullable<float> PercentageTax { get; set; }
        public Nullable<float> PercentageDiscount { get; set; }
    
        public virtual Store_Address Store_Address { get; set; }
        public virtual Store_OutAction Store_OutAction { get; set; }
        public virtual Store_Product Store_Product { get; set; }
        public virtual Store_ProductBlock Store_ProductBlock { get; set; }
        public virtual Users Users { get; set; }
    }
}
