//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emikon.Parkon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Authorization
    {
        public long Id { get; set; }
        public string SysCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string VarStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SetUserId { get; set; }
        public Nullable<long> C0 { get; set; }
        public Nullable<long> C1 { get; set; }
        public Nullable<long> C2 { get; set; }
        public Nullable<long> C3 { get; set; }
        public Nullable<long> C4 { get; set; }
        public Nullable<long> C5 { get; set; }
        public Nullable<long> C6 { get; set; }
        public Nullable<long> C7 { get; set; }
        public Nullable<long> C8 { get; set; }
        public Nullable<long> C9 { get; set; }
        public Nullable<long> C10 { get; set; }
        public Nullable<long> C11 { get; set; }
        public Nullable<long> C12 { get; set; }
        public Nullable<long> C13 { get; set; }
        public Nullable<long> C14 { get; set; }
        public Nullable<long> C15 { get; set; }
        public Nullable<long> C16 { get; set; }
        public Nullable<long> C17 { get; set; }
        public Nullable<long> C18 { get; set; }
        public Nullable<long> C19 { get; set; }
        public Nullable<long> C20 { get; set; }
        public Nullable<long> C21 { get; set; }
        public Nullable<long> C22 { get; set; }
        public Nullable<long> C23 { get; set; }
        public Nullable<long> C24 { get; set; }
        public Nullable<long> C25 { get; set; }
        public Nullable<long> C26 { get; set; }
        public Nullable<long> C27 { get; set; }
        public Nullable<long> C28 { get; set; }
        public Nullable<long> C29 { get; set; }
        public Nullable<long> C30 { get; set; }
        public Nullable<long> C31 { get; set; }
        public Nullable<long> C32 { get; set; }
        public Nullable<long> C33 { get; set; }
        public Nullable<long> C34 { get; set; }
        public Nullable<long> C35 { get; set; }
        public Nullable<long> C36 { get; set; }
        public Nullable<long> C37 { get; set; }
        public Nullable<long> C38 { get; set; }
        public Nullable<long> C39 { get; set; }
        public Nullable<long> C40 { get; set; }
        public Nullable<long> C41 { get; set; }
        public Nullable<long> C42 { get; set; }
        public Nullable<long> C43 { get; set; }
        public Nullable<long> C44 { get; set; }
        public Nullable<long> C45 { get; set; }
        public Nullable<long> C46 { get; set; }
        public Nullable<long> C47 { get; set; }
        public Nullable<long> C48 { get; set; }
        public Nullable<long> C49 { get; set; }
        public Nullable<long> C50 { get; set; }
        public Nullable<long> C51 { get; set; }
        public Nullable<long> C52 { get; set; }
        public Nullable<long> C53 { get; set; }
        public Nullable<long> C54 { get; set; }
        public Nullable<long> C55 { get; set; }
        public Nullable<long> C56 { get; set; }
        public Nullable<long> C57 { get; set; }
        public Nullable<long> C58 { get; set; }
        public Nullable<long> C59 { get; set; }
        public Nullable<long> C60 { get; set; }
        public Nullable<long> C61 { get; set; }
        public Nullable<long> C62 { get; set; }
        public Nullable<long> C63 { get; set; }
        public Nullable<long> C64 { get; set; }
        public Nullable<long> C65 { get; set; }
        public Nullable<long> C66 { get; set; }
        public Nullable<long> C67 { get; set; }
        public Nullable<long> C68 { get; set; }
        public Nullable<long> C69 { get; set; }
        public Nullable<long> C70 { get; set; }
        public Nullable<long> C71 { get; set; }
        public Nullable<long> C72 { get; set; }
        public Nullable<long> C73 { get; set; }
        public Nullable<long> C74 { get; set; }
        public Nullable<long> C75 { get; set; }
        public Nullable<long> C76 { get; set; }
        public Nullable<long> C77 { get; set; }
        public Nullable<long> C78 { get; set; }
        public Nullable<long> C79 { get; set; }
        public Nullable<long> C80 { get; set; }
        public Nullable<long> C81 { get; set; }
        public Nullable<long> C82 { get; set; }
        public Nullable<long> C83 { get; set; }
        public Nullable<long> C84 { get; set; }
        public Nullable<long> C85 { get; set; }
        public Nullable<long> C86 { get; set; }
        public Nullable<long> C87 { get; set; }
        public Nullable<long> C88 { get; set; }
        public Nullable<long> C89 { get; set; }
        public Nullable<long> C90 { get; set; }
        public Nullable<long> C91 { get; set; }
        public Nullable<long> C92 { get; set; }
        public Nullable<long> C93 { get; set; }
        public Nullable<long> C94 { get; set; }
        public Nullable<long> C95 { get; set; }
        public Nullable<long> C96 { get; set; }
        public Nullable<long> C97 { get; set; }
        public Nullable<long> C98 { get; set; }
        public Nullable<long> C99 { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
